#!/bin/zsh

# This doesn't completely work yet.  The goal is to have an option to run Maven commands via Docker, e.g. "./mvnd clean install"

docker run -v ~/.m2:/var/maven/.m2 -v $PWD:/quill-java -w /quill-java -ti --rm -e MAVEN_CONFIG=/var/maven/.m2 maven:3.8.4 mvn -Dbasedir=/quill-java -Duser.home=/var/maven